-- Create the rates table
create table public.rates (
  id bigint generated by default as identity primary key,
  metal_type text unique not null,
  price numeric not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Turn on Realtime for this table
alter publication supabase_realtime add table public.rates;

-- Insert initial data
insert into public.rates (metal_type, price)
values 
  ('gold_24k', 72500),
  ('gold_22k', 68000),
  ('silver', 85000)
on conflict (metal_type) do update 
set price = excluded.price;

-- Create a policy to allow public read access
alter table public.rates enable row level security;

create policy "Enable read access for all users"
on public.rates for select
to authenticated, anon
using (true);

-- Create a policy to allow updates (Warning: strictly for demo/admin, secure this later!)
create policy "Enable update for all users"
on public.rates for update
to authenticated, anon
using (true)
with check (true);
